@echo off
echo Iniciando BioSync DSP V3.0...

echo Iniciando Backend (Motor de Audio Python)...
start cmd /k "cd backend && python -m uvicorn server:app --reload --port 8000"

echo Iniciando Frontend (Interfaz de Usuario React)...
start cmd /k "cd frontend && npm run dev"
